### ISSUE TITLE
terra-dev breaks divraster

### ISSUE THREAD

**Issue by rhijmans** [flaviomoc/DMSD#2]
The development version of "terra" breaks "divraster". This is because, in the unit tests, you use the raw interface like this

```
@ptr$hasValues
@ptr$range_min
```
That is not a stable and secure interface. Can you please these methods instead?

```
hasValues()
minmax()
```

**Comment by flaviomoc** [comment]
Thank you for your feedback! The unit tests have been updated according to your recommendation.
